submit50:
  files: &submit50_files
    - !exclude "*"
    - !require problem1.py
    - !require problem2.py
    - !require problem3.py
    - !require problem4.py
  style: true

check50:
  files: *submit50_files
