submit50:
  files: &submit50_files
    - !exclude "*"
    - !require problem1.py
    - !require problem2.py
    - !require problem3.py
    - !require problem4.py
    - !require problem5.py
    - !require problem6.py
    - !require problem7.py
    - !require problem8.py
    - !require problem9.py
    - !require problem10.py
  style: true

check50:
  files: *submit50_files
